# Generated by Django 5.1.1 on 2025-04-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('property', '0002_alter_property_owner_propertyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_properties',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='property.property'),
        ),
    ]
