# Generated by Django 5.1.1 on 2025-03-24 13:40

import django.db.models.deletion
import property.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Property Listing', max_length=100)),
                ('block', models.CharField(blank=True, max_length=20, null=True)),
                ('street_name', models.CharField(max_length=100)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(default='Singapore', max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField(default=0, validators=[property.models.validate_non_negative])),
                ('bathrooms', models.IntegerField(default=0, validators=[property.models.validate_non_negative])),
                ('square_feet', models.IntegerField(default=0, validators=[property.models.validate_non_negative])),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
