# Generated by Django 5.1.1 on 2025-03-23 13:30

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('city', models.CharField(default='Singapore', max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField(default=0, validators=[property.models.validate_non_negative])),
                ('bathrooms', models.IntegerField(default=0, validators=[property.models.validate_non_negative])),
                ('square_feet', models.IntegerField(default=0, validators=[property.models.validate_non_negative])),
            ],
        ),
    ]
