# Generated by Django 5.1.1 on 2025-03-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
