# Generated by Django 5.1.7 on 2025-04-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_amenities_property_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
    ]
