# Generated by Django 5.1.7 on 2025-04-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HDB', 'HDB'), ('Condo', 'Condo'), ('Landed', 'Landed'), ('Studio', 'Studio')], default='HDB', max_length=50),
        ),
    ]
