# Generated by Django 5.1.7 on 2025-04-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_amenities_property_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
    ]
