# Generated by Django 5.1.7 on 2025-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_propertyimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
