# Generated by Django 5.1.1 on 2025-04-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_propertyrequest_amenities_propertyrequest_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(choices=[('new', 'New Property'), ('update', 'Update Existing Property')], default='new', max_length=20),
        ),
    ]
