# Generated by Django 5.1.7 on 2025-04-12 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_propertyrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='propertyrequest_images/'),
            preserve_default=False,
        ),
    ]
