# Generated by Django 5.1.7 on 2025-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_propertyrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='propertyrequest_images/'),
        ),
    ]
