# Generated by Django 5.2 on 2025-04-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_propertyrequest_image_propertyrequestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_images', to='property.propertyrequest'),
        ),
    ]
