# Generated by Django 5.2 on 2025-04-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_propertyrequestimage_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.propertyrequest'),
        ),
    ]
