# Generated by Django 5.2 on 2025-04-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_property_owner_alter_propertyrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
