# Generated by Django 5.2 on 2025-04-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0020_alter_propertyrequest_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="amenities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="propertyrequest",
            name="amenities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
