# Generated by Django 5.1.7 on 2025-04-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
                ('flat_type', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_commence_date', models.IntegerField()),
                ('remaining_lease', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['town'], name='data_manage_town_409f1a_idx'), models.Index(fields=['flat_type'], name='data_manage_flat_ty_bd9673_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResaleFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=50)),
                ('flat_type', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('storey_range', models.CharField(max_length=20)),
                ('floor_area_sqm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('flat_model', models.CharField(max_length=50)),
                ('lease_commence_date', models.IntegerField()),
                ('remaining_lease', models.CharField(max_length=50)),
                ('resale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['town'], name='data_manage_town_f8ce71_idx'), models.Index(fields=['flat_type'], name='data_manage_flat_ty_a628c4_idx'), models.Index(fields=['month'], name='data_manage_month_3554f3_idx')],
            },
        ),
    ]
