# Generated by Django 5.1.7 on 2025-04-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResaleFlat',
        ),
        migrations.AlterModelOptions(
            name='rentalflat',
            options={'verbose_name': 'Data.gov.sg Dataset', 'verbose_name_plural': 'Data.gov.sg Datasets'},
        ),
        migrations.RemoveIndex(
            model_name='rentalflat',
            name='data_manage_town_409f1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentalflat',
            name='data_manage_flat_ty_bd9673_idx',
        ),
        migrations.RenameField(
            model_name='rentalflat',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='block',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='flat_type',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='lease_commence_date',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='remaining_lease',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='town',
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='record_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
