# Generated by Django 5.1.7 on 2025-04-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_delete_resaleflat_alter_rentalflat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalflat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental Flat', 'verbose_name_plural': 'Rental Flats'},
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='data',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='block',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='flat_type',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='lease_commence_date',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='remaining_lease',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='street_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='town',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
