# Generated by Django 5.1.7 on 2025-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_alter_rentalflat_options_remove_rentalflat_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalflat',
            name='lease_commence_date',
        ),
        migrations.RemoveField(
            model_name='rentalflat',
            name='remaining_lease',
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='rent_approval_date',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalflat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rentalflat',
            name='monthly_rent',
            field=models.CharField(max_length=20),
        ),
    ]
