# Generated by Django 5.1.7 on 2025-04-07 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_remove_rentalflat_lease_commence_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalflat',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rentalflat',
            name='rent_approval_date',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM format', regex='^\\d{4}-(0[1-9]|1[0-2])$')]),
        ),
        migrations.CreateModel(
            name='ResaleFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('town', models.CharField(max_length=50)),
                ('flat_type', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('storey_range', models.CharField(max_length=20)),
                ('floor_area_sqm', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('flat_model', models.CharField(max_length=50)),
                ('lease_commence_date', models.IntegerField()),
                ('remaining_lease', models.CharField(max_length=50)),
                ('resale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resale Flat',
                'verbose_name_plural': 'Resale Flats',
                'ordering': ['-month'],
                'unique_together': {('month', 'block', 'street_name')},
            },
        ),
    ]
