# Generated by Django 5.1.7 on 2025-04-07 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_alter_rentalflat_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalflat',
            name='rent_approval_date',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM format', regex='r^\\d{4}-(0[1-9]|1[0-2])$')]),
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('flat_type', models.CharField(max_length=20)),
                ('storey_range', models.CharField(blank=True, max_length=20, null=True)),
                ('floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('flat_model', models.CharField(blank=True, max_length=50, null=True)),
                ('lease_commence_date', models.IntegerField(blank=True, null=True)),
                ('remaining_lease', models.CharField(blank=True, max_length=50, null=True)),
                ('for_rent', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('rent_approval_date', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM format', regex='r^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('resale_date', models.CharField(blank=True, max_length=7, null=True)),
                ('resale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['for_rent'], name='data_manage_for_ren_bf7877_idx'), models.Index(fields=['for_sale'], name='data_manage_for_sal_e96b09_idx'), models.Index(fields=['town'], name='data_manage_town_8702cc_idx'), models.Index(fields=['flat_type'], name='data_manage_flat_ty_13b53f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('for_rent', True), ('for_sale', True), _connector='OR'), name='at_least_one_purpose'), models.CheckConstraint(condition=models.Q(('for_rent', True), ('for_sale', True), _negated=True), name='mutually_exclusive_purpose')],
            },
        ),
    ]
