# Generated by Django 5.1.7 on 2025-04-07 08:20

from django.db import migrations
import django.core.validators


def migrate_data(apps, schema_editor):
    RentalFlat = apps.get_model('data_management', 'RentalFlat')
    ResaleFlat = apps.get_model('data_management', 'ResaleFlat')
    Flat = apps.get_model('data_management', 'Flat')
    
    # Transfer RentalFlat data
    for rental in RentalFlat.objects.all():
        Flat.objects.create(
            town=rental.town,
            block=rental.block,
            street_name=rental.street_name,
            flat_type=rental.flat_type,
            for_rent=True,
            rent_approval_date=rental.rent_approval_date,
            monthly_rent=rental.monthly_rent,
            created_at=rental.created_at,
            updated_at=rental.updated_at
        )
    
    # Transfer ResaleFlat data
    for resale in ResaleFlat.objects.all():
        Flat.objects.create(
            town=resale.town,
            block=resale.block,
            street_name=resale.street_name,
            flat_type=resale.flat_type,
            storey_range=resale.storey_range,
            floor_area_sqm=resale.floor_area_sqm,
            flat_model=resale.flat_model,
            lease_commence_date=resale.lease_commence_date,
            remaining_lease=resale.remaining_lease,
            for_sale=True,
            resale_date=resale.month,
            resale_price=resale.resale_price,
            created_at=resale.created_at,
            updated_at=resale.updated_at
        )

class Migration(migrations.Migration):
    dependencies = [
        ('data_management', '0006_alter_rentalflat_rent_approval_date_flat'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]