# Generated by Django 5.1.7 on 2025-04-07 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_merge_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='rent_approval_date',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM format', regex='^\\d{4}-(0[1-9]|1[0-2])$')]),
        ),
        migrations.AlterField(
            model_name='rentalflat',
            name='rent_approval_date',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM format', regex='^\\d{4}-(0[1-9]|1[0-2])$')]),
        ),
    ]
