# Generated by Django 5.1.7 on 2025-04-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_alter_flat_rent_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
