# Generated by Django 5.1.7 on 2025-03-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_property_bathrooms_property_bedrooms_property_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
